// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using centro_estudiantes.Data;

#nullable disable

namespace centroestudiantes.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240131121656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("centro_estudiantes.Entities.Choripanes.Choripan", b =>
                {
                    b.Property<int>("IdChoripan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adereso")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FHAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FHBaja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Pan")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoChori")
                        .HasColumnType("int");

                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Verdura")
                        .HasColumnType("longtext");

                    b.HasKey("IdChoripan");

                    b.ToTable("Choripanes");
                });

            modelBuilder.Entity("centro_estudiantes.Entities.Roles.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("centro_estudiantes.Entities.TipoChoris.TipoChori", b =>
                {
                    b.Property<int>("IdTipoChori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TipoDeChori")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTipoChori");

                    b.ToTable("TipoChoris");
                });

            modelBuilder.Entity("centro_estudiantes.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FHAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FHBaja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
